<a href="https://colab.research.google.com/github/JoMihye/Python/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

# `np.ndarray` 속성(attribute)

In [ ]:
arr = np.ones(shape=(2, 3))  # 모든 원소의 값이 1.0인 (2, 3) 모양의 배열
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr.dtype  # 배열의 원소들의 데이터 타입

dtype('float64')

In [ ]:
arr.shape  # 모양(shape): 배열의 각 축(axis)을 따라서 있는 원소의 개수 -> tuple

(2, 3)

In [ ]:
arr.ndim  # 차원(dimension): 배열의 축의 개수.

2

In [ ]:
arr.size  # 크기: 배열의 원소 전체 개수

6

In [ ]:
arr = np.arange(10)  # [0, 10) 범위의 정수들로 이루어진 1차원 배열.
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr.shape

(10,)

In [ ]:
arr.ndim

1

In [ ]:
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(2, 3, 4)

In [ ]:
arr.dtype

dtype('int64')

# indexing

In [ ]:
print(arr)  #> 3차원 배열

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print(arr[0])  #> 2차원 배열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0, 0])  #> 1차원 배열  # arr[0][0]

[1 2 3 4]


In [ ]:
print(arr[0, 0, 0])  #> 원소(scalar)  # arr[0][0][0]

1



*   Python list의 인덱스 사용 방법: `list[i][j]...`
*   numpy ndarray의 인덱스 사용 방법:
    * `array[i][j]...`
    * `array[i, j, ...]`


# slicing

## 1차원 배열 slicing

In [ ]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개로 이루어진 1차원 배열.
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [ ]:
print(arr[1:5])  # [1, 5) 인덱스의 원소들로 이루어진 "1차원 배열"

[12 72  9 75]


In [ ]:
print(arr[:3])  # 배열에서 첫 3개의 원소들을 slicing

[37 12 72]


In [ ]:
print(arr[-3:])  # 배열에서 마지막 3개의 원소들을 slicing

[64 16  1]


In [ ]:
print(arr[0:1])  #> 1차원 배열을 slicing ==> "1차원 배열"!

[37]


In [ ]:
print(arr[0])  # indexing: 원소 1개 선택.

37


## 2차원 배열 slicing

In [ ]:
arr = np.arange(20).reshape((4, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# 첫 2개 row 선택, 모든 column 선택
print(arr[:2, :])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 첫 2개의 row 선택, 첫 3개의 column 선택
print(arr[:2, :3])

[[0 1 2]
 [5 6 7]]


In [ ]:
print(arr[:1, :1])  #> 2차원 배열!

[[0]]


In [ ]:
print(arr[:2])  # arr[:2, :]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
print(arr[:2][:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 3차원 배열 slicing

In [ ]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [ ]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [ ]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [ ]:
print(arr[:1, :, :])  # 3차원 배열 slicing ==> 3차원 배열

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [ ]:
print(arr[0, :, :])  # arr[0]  # 2차원 배열

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print(arr[0])
print(arr[0, 0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
0


# Shape 변경


*   `np.ndarray.reshape(shape)`
*   `np.ndarray.ravel()`
*   `np.ndarray.flatten()`
*   `np.newaxis` 이용


## reshape

In [ ]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# arr_1d를 (4, 3) shape의 2차원 배열로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# reshape의 argument를 전달할 때 자동으로 계산될 수 있는 차원에는 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
arr_2d = arr_1d.reshape((-1, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 2차원 배열 -> 1차원 배열
result = arr_2d.reshape((3 * 4,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## `ravel` vs `flatten`

In [ ]:
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
flattened = arr_2d.flatten()  
# 1차원으로 변환된 배열 "복사본"을 리턴. 
# -> 원본(2차원) 배열과 별개의 배열을 만들어서 리턴.
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
flattened[0] = 123  # 변환된 1차원 배열의 원소를 변경
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [ ]:
print(arr_2d)  # 원본 2차원 배열의 원소에는 영향을 미치지 않음.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
raveled = arr_2d.ravel()
# 1차원으로 변환된 배열의w"를  "Vie리턴.
# -> 원본(2차원) 배열을 단지 모양만 다르게 보여줌.
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
raveled[0] = 123  # 1차원 배열의 원소를 변경
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [ ]:
print(arr_2d)  # 원본(2차원) 배열의 원소에 영향을 미침!

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [ ]:
arr = np.arange(5)  # (5,) shape의 1차원 배열
print(arr)
print('ndim:', arr.ndim)
print('shape:', arr.shape)

[0 1 2 3 4]
ndim: 1
shape: (5,)


In [ ]:
# arr을 (1, 5) shape의 2차원 배열로 변환
result = arr.reshape((1, -1))  # shape=(1, 5)
print(result)

[[0 1 2 3 4]]


In [ ]:
result = arr[np.newaxis, :]
print(result)

[[0 1 2 3 4]]


In [ ]:
# arr을 (5, 1) shape의 2차원 배열로 변환
result = arr.reshape((-1, 1))  # shape=(5, 1)
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
result = arr[:, np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
print(arr_2d)

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [ ]:
result = arr_2d[np.newaxis, :, :]
print(result)

[[[123   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]]


In [ ]:
result = arr_2d[:, :, np.newaxis]
print(result)

[[[123]
  [  1]
  [  2]
  [  3]]

 [[  4]
  [  5]
  [  6]
  [  7]]

 [[  8]
  [  9]
  [ 10]
  [ 11]]]


# concatenate


*   `np.concatenate([array1, array2, ...], axis=0)`: 특정 axis(축) 방향으로 이어 붙이기.
*   `np.r_[array1, array2]`: 행(row) 이어 붙이기.
*   `np.c_[array1, array2]`: 열(column) 이어 붙이기.


In [ ]:
# (2, 3) shape 2-d 배열
a1 = np.arange(6).reshape((2, 3))
print(a1)

[[0 1 2]
 [3 4 5]]


In [ ]:
# (1, 3) shape 2-d 배열
a2 = np.array([[10, 20, 30]])
print(a2)

[[10 20 30]]


In [ ]:
# (2, 1) shape 2-d 배열
a3 = np.array([[11], [22]])
print(a3)

[[11]
 [22]]


In [ ]:
np.concatenate([a1, a2], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [ ]:
np.r_[a1, a2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [ ]:
np.concatenate([a1, a3], axis=1)

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 22]])

In [ ]:
np.c_[a1, a3]

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 22]])

# Broadcasting


*   `np.ndarray`의 산술 연산(+, -, *, /, ...)은 같은 위치(인덱스)의 원소들끼리(element-wise) 연산이 수행됨.
*   서로 다른 shape을 갖는 배열들끼리 산술 연산이 가능한 경우. -> broadcast 가능.


In [ ]:
a = np.array([1, 2, 3])     # (3,) shape의 1d 배열
b = np.array([1, 2, 3, 4])  # (4,) shape의 1d 배열
# a + b
#> ValueError 발생 - broadcast가 불가능.

## ndarray와 scalar의 연산

In [ ]:
a + 10

array([11, 12, 13])

In [ ]:
a2 = np.arange(6).reshape((2, 3))
print(a2)

[[0 1 2]
 [3 4 5]]


In [ ]:
a2 + 10

array([[10, 11, 12],
       [13, 14, 15]])

# 2d 배열과 1d 배열, 또는 2d 배열과 2d 배열에서의 broadcast

In [ ]:
a = np.arange(6).reshape((2, 3))  # (2, 3)
print(a)
b = np.arange(10, 40, 10)  # (3,)
print(b)

[[0 1 2]
 [3 4 5]]
[10 20 30]


In [ ]:
a + b
# (3,) shape 1d --> (1, 3) shape 2d --> (2, 3) shape broadcast

array([[10, 21, 32],
       [13, 24, 35]])

In [ ]:
c = np.array([10, 20])
# a + c
#> ValueError: broadcast가 불가능한 경우.

In [ ]:
d = c[:, np.newaxis]
print(d)

[[10]
 [20]]


In [ ]:
a + d

array([[10, 11, 12],
       [23, 24, 25]])

## broadcast 활용


*   표준화(standardization): 평균이 0이 되고, 표준편차가 1이 되도록 변수들의 스케일을 변환하는 것.
*   정규화(normalization): 최솟값이 0이 되고, 최댓값이 1이 되도록 변수들의 스케일을 변환하는 것. min-max-scaling


## 표준화

In [ ]:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
mu = np.mean(x)  # 평균
print(mu)

3.0


In [ ]:
sigma = np.std(x)  # 표준편차
print(sigma)

1.4142135623730951


In [ ]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
print('평균:', np.mean(x_scaled))
print('표준편차:', np.std(x_scaled))

평균: 0.0
표준편차: 0.9999999999999999


## 정규화

In [ ]:
x_max = np.max(x)
x_min = np.min(x)
print('max:', x_max, ', min:', x_min)

max: 5 , min: 1


In [ ]:
x_scaled = (x - x_min) / (x_max - x_min)
print(x_scaled)

[0.   0.25 0.5  0.75 1.  ]


## 2차원 배열에서의 표준화, 정규화

In [ ]:
# (3, 2)
x = np.arange(1, 7).reshape((3, 2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
np.mean(x)  # axis=None(기본값)

3.5

In [ ]:
np.mean(x, axis=0)  # (1, 3, 5)의 평균, (2, 4, 6)의 평균

array([3., 4.])

In [ ]:
np.mean(x, axis=0, keepdims=True)

array([[3., 4.]])

In [ ]:
np.mean(x, axis=1)  # (1, 3)의 평균, (3, 4)의 평균, (5, 6)의 평균

array([1.5, 3.5, 5.5])

In [ ]:
np.mean(x, axis=1, keepdims=True)

array([[1.5],
       [3.5],
       [5.5]])

In [ ]:
# 표준화
mu = np.mean(x, axis=0, keepdims=True)  # 평균
sigma = np.std(x, axis=0, keepdims=True)  # 표준편차
x_scaled = (x - mu) / sigma
print(x_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [ ]:
# 정규화
x_max = np.max(x, axis=0, keepdims=True)  # 최댓값
x_min = np.min(x, axis=0, keepdims=True)  # 최솟값
x_scaled = (x - x_min) / (x_max - x_min)
print(x_scaled)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [ ]:
df = pd.DataFrame(x, columns=['length', 'width'])
df

length  width
0       1      2
1       3      4
2       5      6

In [ ]:
df.mean(axis=0)

length    3.0
width     4.0
dtype: float64

In [ ]:
df.mean(axis=1)

0    1.5
1    3.5
2    5.5
dtype: float64

In [ ]:
df.drop(labels=1, axis=0)  # axis: label이 있는 축.

length  width
0       1      2
2       5      6

In [ ]:
df.drop(index=1)

length  width
0       1      2
2       5      6

In [ ]:
df.drop(labels='length', axis=1)

width
0      2
1      4
2      6

In [ ]:
df.drop(columns='length')

width
0      2
1      4
2      6

## Exercise

*   seaborn 패키지의 iris 데이터 셋을 로드.
*   iris DataFrame에서 species 컬럼을 삭제.
*   위 DataFrame의 값들로만 이루어진 2차원 배열을 만듦.
*   같은 변수(컬럼)끼리 표준화, 정규화.

In [ ]:
iris = sns.load_dataset('iris')

In [ ]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
x = iris.drop(columns='species')
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
x.index  # row label

RangeIndex(start=0, stop=150, step=1)

In [ ]:
x.columns  # column label

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [ ]:
x = x.values  # 값들로만 이루어진 2차원 배열(2d ndarray)

In [ ]:
x.shape

(150, 4)

In [ ]:
mu = np.mean(x, axis=0, keepdims=True)  # 각 변수들의 평균
print(mu)

[[5.84333333 3.05733333 3.758      1.19933333]]


In [ ]:
sigma = np.std(x, axis=0, keepdims=True)  # 각 변수들의 표준편차
print(sigma)

[[0.82530129 0.43441097 1.75940407 0.75969263]]


In [ ]:
x_scaled = (x - mu) / sigma  # 각 변수들끼리 표준화
print(x_scaled[:5, :])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [ ]:
np.mean(x_scaled, axis=0)

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [ ]:
np.std(x_scaled, axis=0)

array([1., 1., 1., 1.])

In [ ]:
x_max = np.max(x, axis=0, keepdims=True)  # 각 변수들에서 최댓값
print(x_max)

[[7.9 4.4 6.9 2.5]]


In [ ]:
x_min = np.min(x, axis=0, keepdims=True)  # 각 변수들에서 최솟값
print(x_min)

[[4.3 2.  1.  0.1]]


In [ ]:
x_scaled = (x - x_min) / (x_max - x_min)  # 정규화(min-max scaling)
print(x_scaled[:5, :])

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [ ]:
np.max(x_scaled, axis=0)

array([1., 1., 1., 1.])

In [ ]:
np.min(x_scaled, axis=0)

array([0., 0., 0., 0.])

# 행렬 곱(dot product)

In [ ]:
# 같은 인덱스의 원소들끼리의 곱셈
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

## 1차원 배열에서의 행렬 곱

In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

In [ ]:
a @ b

12

In [ ]:
np.dot(a, b)  # 함수

12

In [ ]:
a.dot(b)  # ndarray 메서드

12

## 2차원 배열에서의 행렬 곱

`(i, j) @ (j, k) = (i, k)`


In [ ]:
a = np.arange(1, 7).reshape((2, 3))
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.ones(shape=(3, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a @ b  # (2, 3) @ (3, 2) = (2, 2)

array([[ 6.,  6.],
       [15., 15.]])

In [ ]:
b @ a  # (3, 2) @ (2, 3) = (3, 3)

array([[5., 7., 9.],
       [5., 7., 9.],
       [5., 7., 9.]])

## 2차원 배열과 1차원 배열의 행렬 곱

```
(i, j) @ (j,) = (i,)      # 2D @ 1D = 1D
(i, j) @ (j, 1) = (i, 1)  # 2D @ 2D = 2D
````


In [ ]:
a  # (2, 3) shape

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([1, 2, 1])

In [ ]:
a @ b  # (2, 3) @ (3,) = (2,)

array([ 8, 20])

In [ ]:
c = np.array([[1],
              [2],
              [1]])  # (3, 1)

In [ ]:
a @ c  # (2, 3) @ (3, 1) = (2, 1)

array([[ 8],
       [20]])

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b)

[1 2 1]


In [ ]:
a @ b[:, np.newaxis]  # a @ c

array([[ 8],
       [20]])

# 행렬의 transpose

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]
